name: CI Build

# Trigger on pull request creation, update, and on pushes to the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || 'x86_64-unknown-linux-gnu' || 'x86_64-apple-darwin' }}
        components: clippy

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Check clippy lints
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Install dependencies
      run: cargo fetch

    - name: Build
      run: cargo build --release
